site_name: PlantVarFilter Documentation
site_url: https://github.com/AHMEDY3DGENOME
repo_url: https://github.com/AHMEDY3DGENOME/PlantVarFilter.git
repo_name: GitHub
theme:
  name: material
  features:
    - navigation.tabs
    - navigation.indexes
    - content.code.copy

nav:
  - Home: docs/index.md
  - Usage: docs/usage.md
  - Configuration: docs/config.md
  - Gallery: docs/gallery.md

markdown_extensions:
  - toc:
      permalink: true
  - tables
  - admonition
  - codehilite
  - footnotes
  - pymdownx.highlight
  - pymdownx.superfences
  - pymdownx.tabbed
  - pymdownx.details

extra_css:
  - stylesheets/extra.css  # optional
