{% set name = "plantvarfilter" %}
{% set version = "0.2.0" %}

package:
  name: {{ "plantvarfilter" }}
  version: {{ "0.2.0" }}

source:
  # Build from your local checkout
  path: ../..

build:
  # Pure Python package
  noarch: python
  # Build via pip (reads pyproject.toml)
  script: {{ PYTHON }} -m pip install . -vv
  entry_points:
    - plantvarfilter = plantvarfilter.main_ui:main
    # Add CLI entry points only if you have cli() functions implemented:
    # - pvf-gwas = plantvarfilter.gwas_pipeline:cli
    # - pvf-batch-gwas = plantvarfilter.batch_gwas:cli

requirements:
  host:
    - python >=3.10
    - pip
    - setuptools
    - wheel

  run:
    - python >=3.10
    # Core scientific stack from conda-forge (keep lower bounds Py3.12-friendly)
    - numpy >=1.26
    - pandas >=2.0
    - scipy >=1.11
    - matplotlib >=3.7
    - scikit-learn >=1.3

    # NGS / bioinformatics tools from bioconda/conda-forge
    - bcftools
    - samtools
    - htslib
    - tabix
    - plink
    - plink2
    - bwa
    - bowtie2
    - fastp
    - fastqc
    - minimap2
    - multiqc

test:
  requires:
    - python
  commands:
    # Lightweight smoke test; avoid importing GUI libs here
    - python -c "import plantvarfilter; print('ok')"
    - plantvarfilter --help || true

about:
  home: https://github.com/AHMEDY3DGENOME/PlantVarFilter
  summary: "PlantVarFilter: GWAS & genomic prediction with a desktop GUI."
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - AHMEDY3DGENOME
